### PR TITLE
Non integer binning

### PR DESCRIPTION
**Pull request by francisco-dlp**
Attempt at speeding your function up using numba.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I have fixed a bug a merged with the current RELEASE_next_minor. Tests are passing.

**Comment by francisco-dlp** [comment]
It turns out that `_linear_bin` is 10x faster than `scipy.ndimage.zoom` :)

**Comment by to266** [comment]
well this linear bin does the zooming not in the way I would expect - if a new pixel ends up on the border between two old pixels, only the first of the original is taken into account:

`[1, 2]` rebinned by 0.4 should, in my mind, be something like this (i.e. linear interpolation):
`[1 *0.4, 1*0.4, 1*0.2 + 2*0.2, 2*0.4, 2*0.4]`, but we get instead `[0.4, 0.4, 0.2, 0.8, 0.8]`

**Comment by k8macarthur** [comment]
@to266 you're right, I've been back to check and it's also there in my original function. It seems to be only choosing one of the fractional things rather than combining them...I think i know where the error is. I don't think I fully tested it for binning with a pixel with less than one.

**Comment by k8macarthur** [comment]
I think the simplest I've fixed @to66 's problem. It should work now. 
p.s sorry for the time difference I'm currently in Australia :)

**Pull request merged**
